Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 1234, host: 1234
  config.vm.provision "shell" do |shell|
    shell.inline = "sudo apt-get update -y && sudo apt-get install ansible -y"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
